#!/usr/bin/env bash

echo "# This file is automatically generated. Do not edit."

while IFS= read -r LINE
do
	SPLIT=($LINE)
	VARIANT=$(echo "$LINE" | sed 's/ä/ae/g' | sed 's/ü/ue/g' | sed 's/ö/oe/')
	if [ "$VARIANT" = "$LINE" ]
	then
		VARIANT=""
	else
		VARIANT_SPLIT=($VARIANT)
		VARIANT="${VARIANT}\n${VARIANT_SPLIT[@]:1} ${VARIANT_SPLIT[0]}\n"
	fi

	VARIANT2=$(echo "$LINE" | sed 's/ä/a/g' | sed 's/ü/u/g' | sed 's/ö/o/')
	if [ "$VARIANT2" = "$LINE" ]
	then
		VARIANT2=""
	else
		VARIANT2_SPLIT=($VARIANT2)
		VARIANT2="${VARIANT2}\n${VARIANT2_SPLIT[@]:1} ${VARIANT2_SPLIT[0]}\n"
	fi
	
	echo -e "if\n$LINE\n${SPLIT[@]:1} ${SPLIT[0]}\n${VARIANT}${VARIANT2}  account2 people:$LINE\n"
done
